apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      activeService: demo-service
      previewService: demo-preview
      autoPromotionEnabled: false
