apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: argo-rollouts
spec:
 rules:
 - host: demo.trimawin.de
   http:
     paths:
     - pathType: Prefix
       path: "/"
       backend:
         service:
           name: demo-service
           port:
             number: 8080
