apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: argo-rollouts
spec:
  type: ClusterIP
  ports:
    - port:  8080
      targetPort:  8080
      protocol: TCP
      name: http
  selector:
    app: demo
---
apiVersion: v1
kind: Service
metadata:
  name: demo-preview
  namespace: argo-rollouts
spec:
  type: ClusterIP
  ports:
    - port:  8080
      targetPort:  8080
      protocol: TCP
      name: http
  selector:
    app: demo