apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-demo-preview
spec:
  rules:
  - host: canary-preview.trimawin.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: canary-demo-preview
            port:
              name: http